### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by Hochiss** [M82589933/ThinkPad-X1-Yoga-3rd-Hackintosh#2]
sorry deleted

**Comment by CrazyPegasus** [comment]
hi everyone
Regarding the external monitor issue:
This has something to do with the AppleGraphicsDevicePolicy driver of macOS. It is recommended to add a patch to try using OC boot, as shown below：








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 晚上10:30
收件人:&nbsp;"KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh"<ThinkPad-X1-Yoga-3rd-Hackintosh@noreply.github.com&gt;;
抄送:&nbsp;"山林竹语"<269025198@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh] SSDT-X1Y3-TB3.aml to activate TB3 for LG5K (#2)





 
I am following the discussion at  tylernguyen /
 x1c6-hackintosh , trying different ssdt-tbs.aml patches to make my LG5K light up via TB3 port.  You mentioned:
 
" the kexts made by @CrazyPegasus is attached below. In theory, X1C6 can apply it with no error since there are so many similarities between X1Y3 and X1C6.
 TB3Patch-Crazy.zip"
 
I applied the SSDT-X1Y3.aml only, it seems for my X1C6 the most promising solution (yet not light up LG5K display);  The results as following(BIOS TB3 assistant mode disabled):
  
Boot with closed lid, cannot light-up LG5K;
 
After boot, open lid, native LCD can light up, after login I found although LG5K is not light up, its webcam/Audio/Hub all accessible:
 
under SysPre/PCI, TB's 3 compoents listed:
 
 
IOreg:
 
  
 
Question:
  
Any ideas why LG5K not light up?
 (PS: if I use a USB-C/USB3.1 cable, both native &amp; LG5K can light up without any patches, but LG5K only 2K not 5K)
 
MacBookPro 14,1 said to be able to single max. 5K; yet I closed the lid boot not able to light up; does this matter?
 
What is in fact the most essential in ssdt patches, in order to activate TB3? (hotplug at next?)
  
Thanks!
 
X1C6, HDR2K, macOS 10.15.6, MacBookPro 14,1

**Comment by Hochiss** [comment]
@CrazyPegasus Thanks for passing by. 
What are the patches, and where, explanation pls? 

PS: Since this post was deleted/closed due to duplication, would you mind to reply to [the original post](https://github.com/KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh/issues/1):   [https://github.com/KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh/issues/1](
https://github.com/KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh/issues/1)

**Comment by CrazyPegasus** [comment]
![12](https://user-images.githubusercontent.com/38367520/92886183-0828c880-f446-11ea-82b5-f8acc0a92b78.png)

**Comment by Hochiss** [comment]
Thanks for your @CrazyPegasus help. not working. I reported details [here.](https://github.com/KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh/issues/1).
